# Generated by Django 2.1.7 on 2020-04-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0008_auto_20190318_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'managed': True},
        ),
    ]
