# Generated by Django 2.1.7 on 2020-04-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0010_historicalvolunteerattendanceitems_historicalvolunteers_volunteerattendanceitems_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvolunteerattendanceitems',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='volunteerattendanceitems',
            name='duration',
        ),
    ]
